package main

func description() {
	print("Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:\n1, 2, 3, 5, 8, 13, 21, 34, 55, 89, …\nFind the sum of all the even-valued terms in the sequence which do not exceed four million.\n\n")
}

func analysis() {
	print("I don't like this format.")
}

func main() {
	print("Test.")
}
